/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	filerestorev1alpha1 "kubevirt.io/api/filerestore/v1alpha1"
	scheme "kubevirt.io/client-go/kubevirt/scheme"
)

// VirtualMachineFileRestoresGetter has a method to return a VirtualMachineFileRestoreInterface.
// A group's client should implement this interface.
type VirtualMachineFileRestoresGetter interface {
	VirtualMachineFileRestores(namespace string) VirtualMachineFileRestoreInterface
}

// VirtualMachineFileRestoreInterface has methods to work with VirtualMachineFileRestore resources.
type VirtualMachineFileRestoreInterface interface {
	Create(ctx context.Context, virtualMachineFileRestore *filerestorev1alpha1.VirtualMachineFileRestore, opts v1.CreateOptions) (*filerestorev1alpha1.VirtualMachineFileRestore, error)
	Update(ctx context.Context, virtualMachineFileRestore *filerestorev1alpha1.VirtualMachineFileRestore, opts v1.UpdateOptions) (*filerestorev1alpha1.VirtualMachineFileRestore, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualMachineFileRestore *filerestorev1alpha1.VirtualMachineFileRestore, opts v1.UpdateOptions) (*filerestorev1alpha1.VirtualMachineFileRestore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*filerestorev1alpha1.VirtualMachineFileRestore, error)
	List(ctx context.Context, opts v1.ListOptions) (*filerestorev1alpha1.VirtualMachineFileRestoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *filerestorev1alpha1.VirtualMachineFileRestore, err error)
	VirtualMachineFileRestoreExpansion
}

// virtualMachineFileRestores implements VirtualMachineFileRestoreInterface
type virtualMachineFileRestores struct {
	*gentype.ClientWithList[*filerestorev1alpha1.VirtualMachineFileRestore, *filerestorev1alpha1.VirtualMachineFileRestoreList]
}

// newVirtualMachineFileRestores returns a VirtualMachineFileRestores
func newVirtualMachineFileRestores(c *FilerestoreV1alpha1Client, namespace string) *virtualMachineFileRestores {
	return &virtualMachineFileRestores{
		gentype.NewClientWithList[*filerestorev1alpha1.VirtualMachineFileRestore, *filerestorev1alpha1.VirtualMachineFileRestoreList](
			"virtualmachinefilerestores",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *filerestorev1alpha1.VirtualMachineFileRestore {
				return &filerestorev1alpha1.VirtualMachineFileRestore{}
			},
			func() *filerestorev1alpha1.VirtualMachineFileRestoreList {
				return &filerestorev1alpha1.VirtualMachineFileRestoreList{}
			},
		),
	}
}
