/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	guestcommandv1alpha1 "kubevirt.io/api/guestcommand/v1alpha1"
	scheme "kubevirt.io/client-go/kubevirt/scheme"
)

// VirtualMachineGuestCommandsGetter has a method to return a VirtualMachineGuestCommandInterface.
// A group's client should implement this interface.
type VirtualMachineGuestCommandsGetter interface {
	VirtualMachineGuestCommands(namespace string) VirtualMachineGuestCommandInterface
}

// VirtualMachineGuestCommandInterface has methods to work with VirtualMachineGuestCommand resources.
type VirtualMachineGuestCommandInterface interface {
	Create(ctx context.Context, virtualMachineGuestCommand *guestcommandv1alpha1.VirtualMachineGuestCommand, opts v1.CreateOptions) (*guestcommandv1alpha1.VirtualMachineGuestCommand, error)
	Update(ctx context.Context, virtualMachineGuestCommand *guestcommandv1alpha1.VirtualMachineGuestCommand, opts v1.UpdateOptions) (*guestcommandv1alpha1.VirtualMachineGuestCommand, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualMachineGuestCommand *guestcommandv1alpha1.VirtualMachineGuestCommand, opts v1.UpdateOptions) (*guestcommandv1alpha1.VirtualMachineGuestCommand, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*guestcommandv1alpha1.VirtualMachineGuestCommand, error)
	List(ctx context.Context, opts v1.ListOptions) (*guestcommandv1alpha1.VirtualMachineGuestCommandList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *guestcommandv1alpha1.VirtualMachineGuestCommand, err error)
	VirtualMachineGuestCommandExpansion
}

// virtualMachineGuestCommands implements VirtualMachineGuestCommandInterface
type virtualMachineGuestCommands struct {
	*gentype.ClientWithList[*guestcommandv1alpha1.VirtualMachineGuestCommand, *guestcommandv1alpha1.VirtualMachineGuestCommandList]
}

// newVirtualMachineGuestCommands returns a VirtualMachineGuestCommands
func newVirtualMachineGuestCommands(c *GuestcommandV1alpha1Client, namespace string) *virtualMachineGuestCommands {
	return &virtualMachineGuestCommands{
		gentype.NewClientWithList[*guestcommandv1alpha1.VirtualMachineGuestCommand, *guestcommandv1alpha1.VirtualMachineGuestCommandList](
			"virtualmachineguestcommands",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *guestcommandv1alpha1.VirtualMachineGuestCommand {
				return &guestcommandv1alpha1.VirtualMachineGuestCommand{}
			},
			func() *guestcommandv1alpha1.VirtualMachineGuestCommandList {
				return &guestcommandv1alpha1.VirtualMachineGuestCommandList{}
			},
		),
	}
}
