/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	guestcommandv1alpha1 "kubevirt.io/api/guestcommand/v1alpha1"
	scheme "kubevirt.io/client-go/kubevirt/scheme"
)

// VSOCKConfigsGetter has a method to return a VSOCKConfigInterface.
// A group's client should implement this interface.
type VSOCKConfigsGetter interface {
	VSOCKConfigs(namespace string) VSOCKConfigInterface
}

// VSOCKConfigInterface has methods to work with VSOCKConfig resources.
type VSOCKConfigInterface interface {
	Create(ctx context.Context, vSOCKConfig *guestcommandv1alpha1.VSOCKConfig, opts v1.CreateOptions) (*guestcommandv1alpha1.VSOCKConfig, error)
	Update(ctx context.Context, vSOCKConfig *guestcommandv1alpha1.VSOCKConfig, opts v1.UpdateOptions) (*guestcommandv1alpha1.VSOCKConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*guestcommandv1alpha1.VSOCKConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*guestcommandv1alpha1.VSOCKConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *guestcommandv1alpha1.VSOCKConfig, err error)
	VSOCKConfigExpansion
}

// vSOCKConfigs implements VSOCKConfigInterface
type vSOCKConfigs struct {
	*gentype.ClientWithList[*guestcommandv1alpha1.VSOCKConfig, *guestcommandv1alpha1.VSOCKConfigList]
}

// newVSOCKConfigs returns a VSOCKConfigs
func newVSOCKConfigs(c *GuestcommandV1alpha1Client, namespace string) *vSOCKConfigs {
	return &vSOCKConfigs{
		gentype.NewClientWithList[*guestcommandv1alpha1.VSOCKConfig, *guestcommandv1alpha1.VSOCKConfigList](
			"vsockconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *guestcommandv1alpha1.VSOCKConfig { return &guestcommandv1alpha1.VSOCKConfig{} },
			func() *guestcommandv1alpha1.VSOCKConfigList { return &guestcommandv1alpha1.VSOCKConfigList{} },
		),
	}
}
