//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRestoreSource) DeepCopyInto(out *FileRestoreSource) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(FileRestoreSourcePVC)
		**out = **in
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(FileRestoreSourceSnapshot)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(FileRestoreSourceHost)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRestoreSource.
func (in *FileRestoreSource) DeepCopy() *FileRestoreSource {
	if in == nil {
		return nil
	}
	out := new(FileRestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRestoreSourceHost) DeepCopyInto(out *FileRestoreSourceHost) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRestoreSourceHost.
func (in *FileRestoreSourceHost) DeepCopy() *FileRestoreSourceHost {
	if in == nil {
		return nil
	}
	out := new(FileRestoreSourceHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRestoreSourcePVC) DeepCopyInto(out *FileRestoreSourcePVC) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRestoreSourcePVC.
func (in *FileRestoreSourcePVC) DeepCopy() *FileRestoreSourcePVC {
	if in == nil {
		return nil
	}
	out := new(FileRestoreSourcePVC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRestoreSourceSnapshot) DeepCopyInto(out *FileRestoreSourceSnapshot) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRestoreSourceSnapshot.
func (in *FileRestoreSourceSnapshot) DeepCopy() *FileRestoreSourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(FileRestoreSourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestore) DeepCopyInto(out *VirtualMachineFileRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(VirtualMachineFileRestoreStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestore.
func (in *VirtualMachineFileRestore) DeepCopy() *VirtualMachineFileRestore {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineFileRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestoreList) DeepCopyInto(out *VirtualMachineFileRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineFileRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestoreList.
func (in *VirtualMachineFileRestoreList) DeepCopy() *VirtualMachineFileRestoreList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineFileRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestoreSpec) DeepCopyInto(out *VirtualMachineFileRestoreSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestoreSpec.
func (in *VirtualMachineFileRestoreSpec) DeepCopy() *VirtualMachineFileRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestoreStatus) DeepCopyInto(out *VirtualMachineFileRestoreStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestoreStatus.
func (in *VirtualMachineFileRestoreStatus) DeepCopy() *VirtualMachineFileRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestoreStatus)
	in.DeepCopyInto(out)
	return out
}
